project_id = "fwxfhupzkjjbodymckrl"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.verify-payment]
    verify_jwt = false
  [functions.send-email]
    verify_jwt = false
